"""empty message

Revision ID: 6acc6a778524
Revises: a1b04adc83b5
Create Date: 2023-04-01 19:28:01.447611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6acc6a778524'
down_revision = 'a1b04adc83b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels_list',
    sa.Column('hotelid', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=60), nullable=True),
    sa.Column('rooms', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('hotelid')
    )
    with op.batch_alter_table('hotel_bookings', schema=None) as batch_op:
        batch_op.alter_column('hotel_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=60),
               nullable=True)
        batch_op.alter_column('check_in_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('check_out_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('num_guests',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cust_fname',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=60),
               nullable=True)
        batch_op.alter_column('cust_lname',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=60),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_bookings', schema=None) as batch_op:
        batch_op.alter_column('cust_lname',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('cust_fname',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('num_guests',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('check_out_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('check_in_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('hotel_name',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=255),
               nullable=False)

    op.drop_table('hotels_list')
    # ### end Alembic commands ###
