"""empty message

Revision ID: 4a30ee58239f
Revises: 
Create Date: 2023-03-06 03:36:57.297678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a30ee58239f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_bookings',
    sa.Column('bookingid', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=60), nullable=True),
    sa.Column('check_in_date', sa.DATE(), nullable=True),
    sa.Column('check_out_date', sa.DATE(), nullable=True),
    sa.Column('num_guests', sa.Integer(), nullable=True),
    sa.Column('cust_fname', sa.String(length=60), nullable=True),
    sa.Column('cust_lname', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('bookingid')
    )
    op.drop_table('bookings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('booking_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('check_in_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_out_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('num_guests', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cust_fname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cust_lname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('booking_id', name='bookings_pkey')
    )
    op.drop_table('hotel_bookings')
    # ### end Alembic commands ###
