"""empty message

Revision ID: a1b04adc83b5
Revises: 4a30ee58239f
Create Date: 2023-03-06 07:58:51.354074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b04adc83b5'
down_revision = '4a30ee58239f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    with op.batch_alter_table('hotel_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookingid', sa.Integer(), nullable=False))
        batch_op.alter_column('hotel_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=60),
               nullable=True)
        batch_op.alter_column('check_in_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('check_out_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('num_guests',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cust_fname',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=60),
               nullable=True)
        batch_op.alter_column('cust_lname',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=60),
               nullable=True)
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('cust_lname',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('cust_fname',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('num_guests',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('check_out_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('check_in_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('hotel_name',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('bookingid')

    op.create_table('bookings',
    sa.Column('booking_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('check_in_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_out_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('num_guests', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cust_fname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cust_lname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('booking_id', name='bookings_pkey')
    )
    # ### end Alembic commands ###
